/* LearnFlow MCP Apps panel. All user data goes through the authenticated host bridge. */
(() => {
 'use strict';
 const $=id=>document.getElementById(id), h=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const token=document.querySelector('meta[name="learnflow-ui-token"]').content;
 const pending=new Map();let sequence=0,ready=false,parentOrigin='*',tab='learn',filter='all',activeCourse='',questionIndex=0,answers={},lastFocus=null,toastTimer;
 let state={actor:{},strategies:[],selectedStrategies:[],preferences:{},assets:[],drafts:[],courses:[],community:[],usage:{},capabilities:{}};
 const paths={book:'M4 5h6a3 3 0 0 1 3 3v13a4 4 0 0 0-4-2H4V5Zm16 0h-4a3 3 0 0 0-3 3v13a4 4 0 0 1 4-2h3V5Z',cards:'m6 3 13 3-4 16L2 18 6 3Zm4 0h10v15M6 10l7 2m-8 3 6 1',leaf:'M5 20c0-6 4-11 12-13M4 13C4 5 15 3 21 3c0 11-6 17-13 14M10 13l-1-4m5 1 4 1',chat:'M4 4h16v12H9l-5 4V4Zm4 4h8m-8 4h5',layers:'m12 3 9 5-9 5-9-5 9-5Zm-9 9 9 5 9-5m-18 5 9 5 9-5',route:'M5 5h5a4 4 0 1 1 0 8H8a4 4 0 1 0 0 8h11M3 5a2 2 0 1 0 4 0 2 2 0 0 0-4 0M17 19l3 2-3 2',check:'m5 12 4 4L19 6',plus:'M12 5v14M5 12h14',arrow:'M5 12h14m-5-5 5 5-5 5',back:'M19 12H5m5-5-5 5 5 5',close:'m6 6 12 12M6 18 18 6',people:'M8 4a3 3 0 1 0 0 6 3 3 0 0 0 0-6Zm9 1a3 3 0 0 1 0 6M2 20v-3a5 5 0 0 1 10 0v3M16 14a4 4 0 0 1 5 4v2',folder:'M3 6h7l2 3h9v11H3V6Z',share:'m8 12 8-6M8 13l8 5M4 10h4v5H4v-5Zm12-7h4v5h-4V3Zm0 13h4v5h-4v-5Z',edit:'m14 5 4 4M4 20l4-1L20 7l-4-4L4 15v5Z',clock:'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18Zm0 4v6l4 2',send:'m3 4 18 8-18 8 4-8-4-8Zm4 8h14',file:'M5 3h9l5 5v13H5V3Zm9 0v6h5M9 13h6m-6 4h6',search:'M10 3a7 7 0 1 0 0 14 7 7 0 0 0 0-14Zm5 12 6 6'};
 const icon=name=>`<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name]||paths.cards}"/></svg>`;
 const button=(label,action,cls='',extra='')=>`<button type="button" class="button ${cls}" data-action="${action}" ${extra}>${label}</button>`;
 const byId=(list,id)=>list.find(item=>item.id===id);
 const kindName=kind=>({strategy:'个人策略',block:'学习块','learning-block':'学习块',learning_block:'学习块',pdf:'PDF',note:'学习笔记'}[kind]||'学习资料');
 const titleOf=a=>a.title||a.card?.title||'学习资料';
 const versionLabel=v=>v?.startsWith('v1-')?'个人版本':'v'+(v||'1');
 const date=value=>value?new Date(value).toLocaleDateString('zh-CN'):'';
 const enabled=id=>(state.selectedStrategies||[]).some(s=>(typeof s==='string'?s:s.id??s.strategyId)===id);
 const list=value=>Array.isArray(value)?value:value?[value]:[];
 const strategyIcon=s=>/root|词根/.test(s.id+s.title)?'leaf':/feynman|socratic|费曼|苏格拉底/.test(s.id+s.title)?'chat':/pbl|map|项目/.test(s.id+s.title)?'route':/retriev|回忆|回想/.test(s.id+s.title)?'layers':'cards';
 function toast(message){clearTimeout(toastTimer);$('toast').textContent=message;$('toast').classList.add('visible');toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),3800)}
 function notify(method,params={}){parent.postMessage({jsonrpc:'2.0',method,params},parentOrigin)}
 function rpc(method,params={}){return new Promise((resolve,reject)=>{if(parent===window){reject(Error('请从 Buddy 对话或本地预览打开学习面板。'));return}const id=++sequence;const timer=setTimeout(()=>{pending.delete(id);reject(Error('连接没有回应。保留当前内容，稍后重试。'))},18000);pending.set(id,{resolve,reject,timer});parent.postMessage({jsonrpc:'2.0',id,method,params},parentOrigin)})}
 function unpack(result){if(result?.isError){const text=result.content?.find(x=>x.type==='text')?.text;let message=text;try{message=JSON.parse(text).message||text}catch{}throw Error(message||'操作未完成，请稍后再试。')}if(result?.structuredContent)return result.structuredContent;const raw=result?.content?.find(x=>x.type==='text')?.text;try{return JSON.parse(raw)}catch{return result}}
 async function call(name,args={}){if(!ready)throw Error('学习面板还在连接，请稍等。');return unpack(await rpc('tools/call',{name,arguments:args}))}
 const action=async(name,payload={})=>{const output=await call('learnflow_app_action',{action:name,payload,uiToken:token});return output?.result??output};
 function merge(next){if(!next||typeof next!=='object')return;for(const key of Object.keys(state))if(next[key]!=null)state[key]=next[key];if(next.workspace)merge(next.workspace);render()}
 async function refresh(){const next=await call('show_learning_workspace');for(const c of next.courses||[]){if(!c.submissions)c.submissions=await action('listSubmissions',{courseId:c.id});if(!c.assignments)c.assignments=await action('listAssignments',{courseId:c.id})}next.assets=(next.assets||[]).map(a=>({...a,title:titleOf(a)}));const catalogueIds=new Set((next.strategies||[]).map(s=>s.id));next.strategies=[...(next.strategies||[]),...next.assets.filter(a=>a.kind==='strategy'&&!catalogueIds.has(a.card.id)).map(a=>({...a.card,assetId:a.id,revision:a.revision}))];next.drafts=(next.drafts||[]).map(a=>({...a,title:titleOf(a)}));next.community=(next.community||[]).map(p=>({...p.card,...p,id:p.id,title:p.card?.title||p.title,description:p.card?.description||p.description}));merge(next);return state}
 function reportSize(){notify('ui/notifications/size-changed',{height:Math.min(1400,Math.max(700,Math.ceil(document.body.getBoundingClientRect().height)))})}
 async function context(){const chosen=state.strategies.filter(s=>enabled(s.id)).map(s=>({id:s.id,title:s.title,version:s.version}));try{await rpc('ui/update-model-context',{content:[{type:'text',text:JSON.stringify({learnflowSelection:chosen,preferences:state.preferences,rule:'只采用本次已启用策略；已关闭策略停止生效。用户未确认前不要持久保存。'})}]})}catch{toast('选择已保存；请在下一条对话中提醒助手采用。')}}
 async function sendMessage(text){const response=await rpc('ui/message',{role:'user',content:[{type:'text',text}]});if(response?.isError)throw Error('宿主没有接收消息，请回到对话中继续。');toast('已交给学习助手，回到对话继续。')}
 function openDialog(title,body,footer=''){lastFocus=document.activeElement;$('dialog-title').textContent=title;$('dialog-content').innerHTML=body;$('dialog-footer').innerHTML=footer;$('dialog-footer').hidden=!footer;$('dialog-error').textContent='';if(!$('dialog').open)$('dialog').showModal();requestAnimationFrame(()=>{$('dialog-content').querySelector('input:not([type=checkbox]),textarea,button')?.focus({preventScroll:true});reportSize()})}
 function closeDialog(){$('dialog').close();lastFocus?.isConnected&&lastFocus.focus({preventScroll:true})}
 function empty(title,copy,cta=''){return `<div class="empty"><div class="card-icon">${icon('book')}</div><h2>${h(title)}</h2><p>${h(copy)}</p>${cta}</div>`}
 function statusPill(text){return `<span class="status-pill">${h(text)}</span>`}
 function card(s,community=false){return `<article class="strategy-card ${enabled(s.id)?'enabled':''}" data-card="${h(s.id)}"><div class="cardtop"><div class="card-icon">${icon(strategyIcon(s))}</div>${community?statusPill('分享卡片'):`<button class="toggle" type="button" role="switch" aria-checked="${enabled(s.id)}" aria-label="${h(s.title)}${enabled(s.id)?'：已启用':'：未启用'}" data-action="toggle-strategy" data-id="${h(s.id)}"></button>`}</div><h3>${h(s.title)}</h3><p>${h(s.description||'查看具体步骤，决定是否适合这次学习。')}</p><div class="card-bottom"><button class="link" data-action="${community?'community-detail':'strategy-detail'}" data-id="${h(s.id)}">看步骤与例子</button>${community?button('采纳','adopt-community','soft',`data-id="${h(s.id)}"`):`<span class="subtle"><small>${h(s.revision?'修订 '+s.revision:versionLabel(s.version))}</small></span>`}</div></article>`}
 function draftBanners(){return (state.drafts||[]).filter(d=>d.status==='draft'||d.status==='pending').map(d=>`<div class="draft-callout"><div class="card-icon">${icon('edit')}</div><div class="grow"><h3>${h(d.title)}</h3><p>草稿还没保存，先看看要不要改。</p></div>${button('检查并保存','review-draft','soft',`data-id="${h(d.id)}"`)}</div>`).join('')}
 function learn(){const preferences=state.preferences||{},started=preferences.onboardingComplete||preferences.goal||preferences.intent;return `<div class="heading"><div><h1>${started?'接着学，你来定节奏。':'今天，学会一点新的。'}</h1></div>${button(icon('edit')+'学习偏好','onboarding','','aria-label="修改学习偏好"')}</div>${draftBanners()}<section class="intro"><div><h2>${started?h(preferences.goal||'先做眼前这一小步'):'不必先想好一整条路。'}</h2><p>${started?'挑一个方法，带着问题回到对话里。':'三个小选择，找到这次学习的起点。之后随时能改。'}</p>${started?`${button(icon('send')+'继续这次学习','start-learning','primary')}<div class="progress-summary">${[preferences.intent,preferences.duration,preferences.guidance].filter(Boolean).map(v=>`<button data-action="onboarding">${h(v)}</button>`).join('')}</div>`:button('选好第一步','onboarding','primary') }</div><div class="paper-art" aria-hidden="true"><div class="sheet"></div><div class="sheet"></div><div class="sheet"><span class="face"><i></i><i></i></span><span class="line"></span><span class="line"></span></div></div></section><div class="section-heading"><h2>这次用什么方法</h2><span class="subtle"><small>${state.strategies.filter(s=>enabled(s.id)).length} 张已启用</small></span></div><div class="filters" aria-label="策略筛选">${[['all','全部'],['selected','已启用'],['exam','应试复盘'],['self','自主学习'],['pbl','项目学习']].map(([key,label])=>`<button data-action="filter" data-filter="${key}" class="${filter===key?'active':''}">${label}</button>`).join('')}</div><div class="card-grid">${state.strategies.filter(s=>filter==='all'||filter==='selected'&&enabled(s.id)||filter!=='selected'&&(s.scene===filter||s.scene==='all'||list(s.tags).join(' ').includes({exam:'应试',self:'自',pbl:'项目'}[filter]))).map(s=>card(s)).join('')||empty('这里还没有卡片','试试其他分类。')}</div>`}
 function assets(){const items=state.assets||[];return `<div class="heading"><div><h1>留下来的，都在这里。</h1></div><div class="row wrap">${button(icon('file')+'保存 PDF','import-pdf')}${button(icon('plus')+'写一份笔记','new-draft','primary')}</div></div>${draftBanners()}${items.length?`<div class="saved-list">${items.map(item=>`<article class="asset-row"><div class="card-icon">${icon(item.kind==='strategy'?'cards':'file')}</div><div class="grow"><h3>${h(item.title)}</h3><p>${h(kindName(item.kind))}${item.revision?' · 修订 '+h(item.revision):''} ${h(date(item.updatedAt||item.createdAt))}</p></div>${button('打开','open-asset','',`data-id="${h(item.id)}"`)}</article>`).join('')}</div>`:empty('一份好用的笔记，也可以是起点。','学习后请助手整理草稿。你检查、修改并确认，它才会出现在这里。',button('自己写一份','new-draft','soft'))}`}
 function courseData(){return byId(state.courses,activeCourse)||state.courses[0]}
 function teacher(course){return course?.ownerId===state.actor.id||course?.teacherId===state.actor.id||course?.role==='teacher'}
 function submissions(course){return course?.submissions||[]}
 function assignments(course){return course?.assignments||[]}
 function classroom(){const course=courseData();if(course)activeCourse=course.id;const isTeacher=teacher(course);return `<div class="heading"><div><h1>一起学，也看见各自的进步。</h1></div><div class="row wrap">${button('加入课程','join-course')}${button(icon('plus')+'创建课程','create-course','primary')}</div></div>${!course?empty('这门课，从一个学习目标开始。','老师创建课程，同学通过邀请码加入。提交哪些学习内容，由学生自己选择。',button('创建第一门课','create-course','soft')):`<div class="course-list">${state.courses.map(c=>`<button class="course-tab ${c.id===course.id?'active':''}" data-action="select-course" data-id="${h(c.id)}">${h(c.title)}</button>`).join('')}</div><section class="course-head"><div class="row between wrap"><h2>${h(course.title)}</h2>${statusPill(isTeacher?'教师':'学生')}</div><p>${h(course.objective||'把目标学会，用自己的作品说明。')}</p><div class="row between wrap"><div class="row wrap"><span class="member-chip">${icon('people')}${(course.memberCount??list(course.members).length)+1} 位参与者</span>${isTeacher?button('邀请同学','invite-course','',''):''}</div>${isTeacher?button('拟一份作业','new-assignment','soft'):button('提交学习过程','submit-evidence','primary')}</div></section><div class="course-grid"><section class="course-section"><h3>${isTeacher?'待你核验的学习过程':'我的学习提交'}</h3>${submissions(course).length?submissions(course).map(s=>`<article class="item-row"><div class="row between"><strong>${h(s.title)}</strong>${statusPill(s.review?'已核验':'待核验')}</div><p>${h(s.student?.displayName||s.studentLabel||s.learnerLabel||'学习提交')} ${h(date(s.createdAt))}</p>${button(isTeacher?'查看与核验':'查看提交','view-submission','',`data-id="${h(s.id)}"`)}</article>`).join(''):`<p class="subtle">${isTeacher?'同学提交后，可以查看选中的对话和学习成果。':'选择要交给老师的片段，其他对话留给自己。'}</p>`}</section><section class="course-section"><h3>针对性作业</h3>${assignments(course).length?assignments(course).map(a=>`<article class="item-row"><div class="row between"><strong>${h(a.title)}</strong>${statusPill(({draft:'草稿',published:'已布置',submitted:'已提交',completed:'已完成',confirmed:'教师已确认'})[a.status]||a.status||'已布置')}</div><p>${h((a.content||a.instructions||'').slice(0,90))}</p>${button('查看作业','view-assignment','',`data-id="${h(a.id)}"`)}</article>`).join(''):`<p class="subtle">${isTeacher?'根据具体的理解缺口布置练习。AI 可以拟草稿，由你确认。':'老师布置的作业会出现在这里。'}</p>`}</section></div>`}`}
 function community(){return `<div class="heading"><div><h1>你的好方法，也许正好帮到别人。</h1></div>${button(icon('share')+'分享一张卡片','share-strategy','primary')}</div>${state.community.length?`<div class="card-grid">${state.community.map(s=>card(s,true)).join('')}</div>`:empty('先分享一张真正用过的卡片。','公开前可以检查内容，个人学习记录不会随卡片一起发布。',button('选择我的策略','share-strategy','soft'))}`}
 function render(){document.querySelectorAll('[data-nav]').forEach(b=>b.setAttribute('aria-current',b.dataset.nav===tab?'page':'false'));$('actor').innerHTML=`<span class="avatar">${h((state.actor.label||'我').slice(0,1))}</span><span>${h(state.actor.label||'我的空间')}</span>`;$('view').innerHTML=({learn,assets,classroom,community})[tab]();reportSize()}
 const questions=[{key:'intent',title:'这次，想先做什么？',choices:[['复盘错题','找到真正卡住的一步'],['学懂一个概念','能用自己的话讲清楚'],['推进一个项目','做出今天看得见的小成果']]},{key:'duration',title:'这一次，留多少时间？',choices:[['15 分钟','先完成一个小块'],['30 分钟','讲解之后，再练一次'],['时间由我决定','不用替我计时']]},{key:'guidance',title:'卡住时，希望怎么帮你？',choices:[['先给一点提示','我想自己再试试'],['直接讲明白','看懂后再自己练'],['先让我讲，再纠错','从我的理解接着往下走']]}];
 function showQuestion(){if(questionIndex>=questions.length){openDialog('就从这里开始',`<h2 class="question-title">选好了，接下来学什么？</h2><div class="tag-list">${Object.values(answers).map(v=>`<span class="tag">${h(v)}</span>`).join('')}</div><label class="field">这次的小目标<input id="learning-goal" maxlength="300" placeholder="比如：弄懂条件概率，自己做对一道题" value="${h(state.preferences.goal||'')}"></label><label class="check"><input type="checkbox" id="save-preferences" checked><span>记住这次的选择，下次也可以改。</span></label>`,button('上一步','previous-question')+button('开始学习','finish-onboarding','primary'));return}const q=questions[questionIndex];openDialog('找到第一步',`<div class="question-progress" aria-hidden="true">${questions.map((_,i)=>`<i class="${i<=questionIndex?'done':''}"></i>`).join('')}</div><p class="question-count">${questionIndex+1} / ${questions.length}</p><h2 class="question-title">${q.title}</h2><div class="question-choices">${q.choices.map(([name,description])=>`<button data-action="answer-question" data-value="${h(name)}"><span>${h(name)}<small>${h(description)}</small></span>${icon(answers[q.key]===name?'check':'arrow')}</button>`).join('')}</div>`,(questionIndex?button('上一步','previous-question'):'')+button('暂时跳过','skip-onboarding'))}
 function formattedSteps(s){return list(s.steps?.length?s.steps:s.instructions).map(step=>Array.isArray(step)?`<strong>${h(step[0])}</strong><br>${h(step[1])}`:typeof step==='object'?`<strong>${h(step.title||'')}</strong><br>${h(step.description||step.text||'')}`:h(step))}
 function formattedExample(examples){return list(examples).map(example=>{if(typeof example==='string')return `<p>${h(example)}</p>`;if(Array.isArray(example))return `<p><strong>${h(example[0])}</strong>${h(example[1])}</p>`;return `<p><strong>${h(example.role||example.label||example.title||'示例')}</strong>${h(example.content||example.text||example.input||example.description||'')}${example.output?'<br>'+h(example.output):''}</p>`}).join('')}
 async function detail(id,shared=false){const sharedItem=shared?byId(state.community,id):null;const s=shared?{...sharedItem.card,...sharedItem}:await call('get_learning_strategy',{id});if(!s)throw Error('没有找到这张卡片，请刷新后再试。');openDialog(s.title,`<div class="row between"><div class="tag-list">${list(s.tags).map(tag=>`<span class="tag">${h(tag)}</span>`).join('')}</div>${statusPill(versionLabel(s.version))}</div><p>${h(s.description)}</p>${s.fits?`<h3>适合什么时候用</h3><p>${h(s.fits)}</p>`:''}<h3>具体怎么学</h3><ol class="steps">${formattedSteps(s).map(step=>`<li>${step}</li>`).join('')||`<li>${h(s.text||'还没有详细步骤，采纳前请先补充。')}</li>`}</ol><h3>比如这样</h3><div class="example">${formattedExample(s.examples||s.example)||'<p>作者还没有补充实例。可以先请助手给一个小例子。</p>'}</div><h3>什么时候需要换个办法</h3><p>${h(list(s.limits).join('\n')||'根据自己的基础和学习材料调整；不能仅凭模型讲解流畅判断已经掌握。')}</p>${s.evidence?`<h3>如何检查是否有用</h3><p>${h(typeof s.evidence==='string'?s.evidence:JSON.stringify(s.evidence))}</p>`:''}${list(s.controls).length?`<h3>你可以改的地方</h3><ul class="readable-list">${s.controls.map(x=>`<li>${h(x)}</li>`).join('')}</ul>`:''}`,shared?button('留下使用反馈','feedback-form','',`data-id="${h(id)}"`)+button('采纳到我的策略','adopt-community','primary',`data-id="${h(id)}"`):button(enabled(id)?'关闭这个方法':'启用这个方法','toggle-strategy','primary',`data-id="${h(id)}"`))}
 function draftForm(draft){const d=draft?{...draft,title:titleOf(draft),markdown:draft.card?.instructions||draft.markdown}: {kind:'learning-block',title:'',markdown:''};$('dialog')._draft=draft||null;openDialog(draft?'检查后，再留下':'写一份学习笔记',`<form id="draft-form"><label class="field">标题<input name="title" maxlength="180" required value="${h(d.title)}" placeholder="给下次的自己一个清楚的标题"></label><label class="field">保存为<select name="kind" ${draft?'disabled':''}><option value="learning-block" ${d.kind==='learning-block'?'selected':''}>学习块</option><option value="strategy" ${d.kind==='strategy'?'selected':''}>个人学习策略</option></select></label><label class="field">内容<textarea name="markdown" rows="9" maxlength="50000" required placeholder="学到了什么？下次该怎么继续？">${h(d.markdown||d.content||'')}</textarea></label><details class="strategy-fields" ${d.kind==='strategy'?'open':''}><summary>策略说明、例子与边界</summary><label class="field">适用情形<input name="description" maxlength="3000" value="${h(draft?.card?.description||'')}" placeholder="在什么问题上，这个方法比较有用"></label><label class="field">使用示例<textarea name="examples" rows="3" maxlength="8000" placeholder="写一个具体的学习例子">${h(list(draft?.card?.examples).join('\n\n'))}</textarea></label><label class="field">适用边界<textarea name="limits" rows="2" maxlength="3000" placeholder="什么时候应该调整或改用其他方法">${h(draft?.card?.limits||'')}</textarea></label></details><label class="check"><input type="checkbox" name="confirmed" required><span>我检查过内容，确认保存到自己的学习资料。</span></label></form>`,button('这次不留',draft?'cancel-draft':'close-dialog','',draft?`data-id="${h(d.id)}"`:'')+button('确认保存','save-draft','primary'));$('dialog')._draft=draft||null}
 async function openAsset(id){const asset=await action('getAsset',{assetId:id});const a=asset.asset||asset;a.title=titleOf(a);openDialog(a.title,`<div class="row between">${statusPill(kindName(a.kind))}<span class="subtle"><small>${h(date(a.updatedAt||a.createdAt))}</small></span></div><div class="divider"></div><div class="content">${h(a.markdown||a.card?.instructions||a.content||'')}</div>`,button('下载内容','download-asset','',`data-id="${h(a.id)}"`)+(a.kind==='strategy'?button('带着这张卡学习','use-asset','primary',`data-id="${h(a.id)}"`):button('接着学这份资料','use-asset','primary',`data-id="${h(a.id)}"`)));$('dialog')._asset=a}
 function createCourseForm(){openDialog('创建课程',`<form id="course-form"><label class="field">课程名称<input name="title" maxlength="160" required placeholder="例如：把概率讲明白"></label><label class="field">希望同学学会什么<textarea name="objective" rows="3" maxlength="4000" required placeholder="例如：用一个新例子，解释条件概率与联合概率的区别"></textarea></label><label class="field">教学方法<select name="teachingStrategy"><option value="formative-evidence">证据与人工核验</option><option value="feynman">解释与追问</option><option value="retrieval">独立回忆与迁移</option></select></label></form>`,button('取消','close-dialog')+button('创建课程','save-course','primary'))}
 function joinCourseForm(){openDialog('加入课程',`<form id="join-form"><label class="field">老师分享的邀请码<input name="inviteCode" maxlength="64" required placeholder="粘贴课程邀请码" autocomplete="off"></label><p>加入后，你仍然自己决定提交哪些内容。</p></form>`,button('取消','close-dialog')+button('确认加入','confirm-join','primary'))}
 function evidenceForm(){const c=courseData();openDialog('选择交给老师的内容',`<form id="evidence-form"><label class="field">这次学习的主题<input name="title" maxlength="160" required placeholder="例如：我现在怎样理解条件概率"></label><label class="field">粘贴你想提交的对话<textarea name="source" rows="5" maxlength="30000" placeholder="每段之间空一行。下一步会让你逐段勾选。"></textarea></label><div class="row">${button('整理成可选片段','prepare-evidence','soft')}</div><div id="evidence-fragments"></div>${state.assets.length?`<h3>也可以附上已保存的学习资料</h3>${state.assets.slice(0,30).map(a=>`<label class="check"><input type="checkbox" name="assetId" value="${h(a.id)}"><span>${h(a.title)}</span></label>`).join('')}`:''}<label class="check"><input type="checkbox" name="confirmed" required><span>确认只提交勾选内容给「${h(c.title)}」的教师。</span></label></form>`,button('取消','close-dialog')+button('确认所选内容并提交','confirm-evidence','primary'));$('dialog')._fragments=[]}
 function submissionDetail(id){const c=courseData(),s=byId(submissions(c),id);if(!s)throw Error('没有找到这份提交。');const msgs=s.messages||s.fragments||[];const review=s.review;openDialog(s.title,`<div class="row between">${statusPill(review?'教师已核验':'待教师核验')}<small>${h(s.student?.displayName||s.studentLabel||s.learnerLabel||'')}</small></div><h3>学生选择的片段</h3>${msgs.map(m=>`<div class="example"><strong>${h(m.role==='assistant'?'AI':m.role==='user'?'学习者':m.role||'学习片段')}</strong><p>${h(m.content||m.text||m)}</p></div>`).join('')||'<p>这份提交使用了学习资料，未附对话片段。</p>'}${list(s.assets).map(a=>`<div class="example"><strong>${h(a.title)}</strong><p>${h(a.markdown||a.content||'')}</p></div>`).join('')}<p class="notice">${s.tokens?.actual!=null?'记录的 Token 用量：'+h(s.tokens.actual)+'。':'本次没有可核验的 Token 用量。'} 掌握程度由学习证据判断。</p>${teacher(c)?`${s.assessment?`<h3>AI 整理的分析草稿</h3><div class="example content">${h(s.assessment)}</div>`:''}<div class="model-action"><h3>需要第二双眼睛？</h3><p>让助手根据这些片段提出待核验项。</p>${button('请 AI 分析学习证据','ask-assessment','',`data-id="${h(id)}"`)}</div><form id="review-form"><label class="field">你核验后的判断<select name="judgment"><option value="pending">还需要练习</option><option value="partial">部分掌握</option><option value="mastered">已有掌握证据</option></select></label><label class="field">依据与下一步<textarea name="feedback" rows="5" required maxlength="12000" placeholder="引用学生的具体表现，再给出一次可行的下一步。">${h(review?.feedback||review?.basis||'')}</textarea></label><label class="check"><input type="checkbox" name="confirmed" required><span>我已人工核验上述判断。</span></label></form>`:review?`<h3>老师的反馈</h3><p>${h(review.feedback||review.basis)}</p>`:''}`,teacher(c)?button('取消','close-dialog')+button('保存核验结果','confirm-review','primary',`data-id="${h(id)}"`):button('关闭','close-dialog'))}
 function assignmentForm(existing=null){const c=courseData();openDialog(existing?'检查作业草稿':'布置一次针对性练习',`<form id="assignment-form"><label class="field">布置给<select name="studentId">${list(c.members).filter(m=>m.role==='student').map(m=>`<option value="${h(m.id||m.userId)}">${h(m.displayName||m.label||m.name||'课程同学')}</option>`).join('')||'<option value="">请先邀请学生加入课程</option>'}</select></label>${button('请 AI 根据学习过程拟草稿','ask-assignment','soft')}<div class="divider"></div><label class="field">作业标题<input name="title" maxlength="160" required value="${h(existing?.title||'')}"></label><label class="field">任务与完成标准<textarea name="content" rows="6" maxlength="12000" required placeholder="做什么、交什么、怎样说明已经学会。">${h(existing?.content||existing?.instructions||'')}</textarea></label><label class="field">截止日期（可选）<input name="due" type="date" value="${h(existing?.due?.slice(0,10)||'')}"></label><label class="check"><input type="checkbox" name="confirmed" required><span>我检查过题目和对象，确认发布作业。</span></label></form>`,button('取消','close-dialog')+button('确认布置','confirm-assignment','primary'));$('dialog')._assignment=existing}
 function assignmentDetail(id){const c=courseData(),a=byId(assignments(c),id);if(!a)throw Error('没有找到这份作业。');if(teacher(c)&&a.status==='draft'){assignmentForm(a);return}openDialog(a.title,`<div class="content">${h(a.content||a.instructions||'')}</div>${a.due?`<p class="notice">截止：${h(date(a.due))}</p>`:''}${a.response?`<h3>学生提交</h3><div class="content">${h(a.response.content||a.response)}</div>`:''}${teacher(c)&&a.status==='submitted'?'<label class="field">确认完成的依据<textarea id="assignment-basis" rows="3" placeholder="根据哪一处表现，确认已达到完成标准"></textarea></label>':''}${!teacher(c)?`<div class="divider"></div><form id="answer-form"><label class="field">我的完成内容<textarea name="content" required rows="5" maxlength="20000" placeholder="留下你的解答、思路或成果链接。"></textarea></label><label class="check"><input name="confirmed" type="checkbox" required><span>确认将本次成果提交给老师。</span></label></form>`:''}`,teacher(c)?(a.status==='submitted'?button('确认已完成','complete-assignment','primary',`data-id="${h(id)}"`):button('关闭','close-dialog')):button('提交作业','submit-assignment','primary',`data-id="${h(id)}"`))}
 function shareForm(){const own=state.assets.filter(a=>a.kind==='strategy');openDialog('分享自己的学习方法',own.length?`<form id="share-form"><label class="field">选择一张个人策略<select name="assetId">${own.map(a=>`<option value="${h(a.id)}">${h(a.title)}</option>`).join('')}</select></label><p>分享所选策略当前版本的内容。先打开它，检查方法、示例与边界。</p><label class="check"><input name="confirmed" type="checkbox" required><span>确认公开这张卡片的内容；已检查并去掉不想公开的信息。</span></label></form>`:empty('先留下一张自己的策略卡。','在学习资料里写下方法，保存为「个人学习策略」，再回来分享。'),own.length?button('取消','close-dialog')+button('确认分享','confirm-share','primary'):button('去写一张','new-draft','primary'))}
 function download(content,mime,name){const url=URL.createObjectURL(new Blob([content],{type:mime}));const link=document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),60000);toast('已请求下载，文件可用设备上的程序打开。')}
 async function openPdf(id){const result=await action('readPdf',{assetId:id}),binary=Uint8Array.from(atob(result.base64),c=>c.charCodeAt(0)),url=URL.createObjectURL(new Blob([binary],{type:'application/pdf'}));openDialog(result.asset.title||result.asset.name,`<div class="empty"><div class="card-icon">${icon('file')}</div><h2>${h(result.asset.name||result.asset.title)}</h2><p>打开 PDF 查看，或下载到自己的设备。</p><div class="row wrap" style="justify-content:center"><a class="button primary" href="${url}" target="_blank" rel="noopener">在浏览器打开</a><a class="button" href="${url}" download="${h(result.asset.name||'学习资料.pdf')}">下载 PDF</a></div></div>`,button('删除这份副本','delete-pdf','danger',`data-id="${h(id)}"`)+button('关闭','close-dialog'));$('dialog').addEventListener('close',()=>setTimeout(()=>URL.revokeObjectURL(url),60000),{once:true})}
 function values(formId){const form=$(formId);if(!form.reportValidity())return null;const data=new FormData(form);data.delete('confirmed');return Object.fromEntries(data)}
 async function changed(message){await refresh();toast(message)}
 const handlers={
  'close-dialog':()=>closeDialog(),
  'onboarding':()=>{questionIndex=0;answers={};for(const q of questions)if(state.preferences[q.key])answers[q.key]=state.preferences[q.key];showQuestion()},
  'answer-question':b=>{answers[questions[questionIndex].key]=b.dataset.value;questionIndex++;showQuestion()},
  'previous-question':()=>{questionIndex=Math.max(0,questionIndex-1);showQuestion()},
  'skip-onboarding':()=>{closeDialog();toast('随时可以点“学习偏好”重新选择。')},
  'finish-onboarding':async()=>{const goal=$('learning-goal').value.trim(),preferences={...answers,goal,onboardingComplete:true};if($('save-preferences').checked){await action('setPreferences',{preferences});await refresh()}else state.preferences=preferences;closeDialog();render();await context();await sendMessage(`我想开始学习。目标：${goal||'先和我一起确定一个具体问题'}。${Object.values(answers).join('；')}。先只问一个问题，帮我走完第一小步；未经我确认不要保存记忆。`)},
  'start-learning':async()=>{await context();await sendMessage(`继续我的 LearnFlow 学习。目标：${state.preferences.goal||'先问我这次想学什么'}。只采用面板当前已启用的策略，先留给我尝试的机会。`)},
  'filter':b=>{filter=b.dataset.filter;render()},
  'strategy-detail':b=>detail(b.dataset.id),
  'community-detail':b=>detail(b.dataset.id,true),
  'toggle-strategy':async b=>{const id=b.dataset.id,on=!enabled(id);const selected=state.strategies.filter(s=>s.id===id?on:enabled(s.id)).map(s=>({id:s.id,title:s.title,version:s.version||''}));await action('setPreferences',{selectedStrategies:selected});await changed(on?'已启用，下轮学习采用这个方法。':'已关闭，下轮学习不再采用。');await context();if($('dialog').open)closeDialog()},
  'import-pdf':()=>openDialog('保存一份值得再读的 PDF',`<form id="pdf-form"><label class="field">选择 PDF<input id="pdf-file" type="file" accept="application/pdf,.pdf" required></label><p>最多 5 MB。确认后会上传到自己的资料库。</p><label class="check"><input type="checkbox" required><span>我确认保存这份资料，供自己学习使用。</span></label></form>`,button('取消','close-dialog')+button('确认保存 PDF','confirm-pdf','primary')),
  'confirm-pdf':async()=>{if(!$('pdf-form').reportValidity())return;const file=$('pdf-file').files[0];if(file.size>5*1024*1024)throw Error('PDF 超过 5 MB，请先压缩或拆成章节。');const bytes=new Uint8Array(await file.arrayBuffer());if(new TextDecoder().decode(bytes.slice(0,5))!=='%PDF-')throw Error('这份文件不是有效的 PDF。');let binary='';for(let i=0;i<bytes.length;i+=16384)binary+=String.fromCharCode(...bytes.subarray(i,i+16384));await action('importPdf',{name:file.name,base64:btoa(binary)});closeDialog();await changed('PDF 已保存，可以随时再打开。')},
  'delete-pdf':b=>openDialog('删除这份 PDF 副本？','<p>这会移除资料库中的副本，不会删除你设备上原有的文件。</p>',button('保留','close-dialog')+button('确认删除','confirm-delete-pdf','danger',`data-id="${h(b.dataset.id)}"`)),
  'confirm-delete-pdf':async b=>{await action('deletePdf',{assetId:b.dataset.id});closeDialog();await changed('资料库里的 PDF 副本已删除。')},
  'new-draft':()=>draftForm(),
  'review-draft':b=>draftForm(byId(state.drafts,b.dataset.id)),
  'save-draft':async()=>{const v=values('draft-form');if(!v)return;let d=$('dialog')._draft;const kind=d?.kind||v.kind;const card={...(d?.card||{}),title:v.title,instructions:v.markdown,description:v.description||'',examples:(v.examples||'').split(/\n\s*\n/).filter(Boolean),limits:v.limits||''};const payload=kind==='strategy'?{kind,card}:{kind,title:v.title,markdown:v.markdown};if(d){const next=await action('updateDraft',{draftId:d.id,expectedRevision:d.revision,...payload});d=next.draft||next;$('dialog')._draft=d}else{const result=await action('createDraft',payload);d=result.draft||result;$('dialog')._draft=d}await action('approveDraft',{draftId:d.id,expectedRevision:d.revision});closeDialog();tab='assets';await changed('保存好了，下次还能打开。')},
  'cancel-draft':async b=>{await action('cancelDraft',{draftId:b.dataset.id,expectedRevision:byId(state.drafts,b.dataset.id)?.revision});closeDialog();await changed('这次没有保存。')},
  'open-asset':b=>byId(state.assets,b.dataset.id)?.kind==='pdf'?openPdf(b.dataset.id):openAsset(b.dataset.id),
  'download-asset':async()=>{const a=$('dialog')._asset;const output=await action('exportAsset',{assetId:a.id,format:'markdown'});download(output.content,output.mimeType,output.filename)},
  'use-asset':async b=>{const a=$('dialog')._asset;closeDialog();await sendMessage(`请继续使用我确认保存的学习资料。先调用 read_learning_asset，id 为 ${b.dataset.id}，标题 ${a.title}。根据资料接着问一个问题。`)},
  'create-course':()=>createCourseForm(),
  'join-course':()=>joinCourseForm(),
  'save-course':async()=>{const v=values('course-form');if(!v)return;const result=await action('createCourse',{title:v.title,objective:v.objective,strategy:v.teachingStrategy,displayName:state.actor.label});activeCourse=(result.course||result).id;closeDialog();await changed('课程已创建，可以邀请同学了。')},
  'confirm-join':async()=>{const v=values('join-form');if(!v)return;const result=await action('joinCourse',{code:v.inviteCode.trim(),displayName:state.actor.label});activeCourse=(result.course||result).id;closeDialog();await changed('已加入课程。')},
  'select-course':b=>{activeCourse=b.dataset.id;render()},
  'invite-course':async()=>{const c=courseData();const invite=await action('createInvite',{courseId:c.id});c.inviteCode=invite.inviteCode||invite.code;openDialog('邀请同学加入',`<h3>${h(c.title)}</h3><p>把邀请码发给同学，在「课程」里选择「加入课程」。</p><div class="notice"><span class="course-code">${h(c.inviteCode||c.code||'')}</span></div>`,button('复制邀请码','copy-invite','primary'))},
  'copy-invite':async()=>{const c=courseData();try{await navigator.clipboard.writeText(c.inviteCode||c.code);toast('邀请码已复制。')}catch{toast('请选中邀请码后复制。')}},
  'submit-evidence':()=>evidenceForm(),
  'prepare-evidence':()=>{const text=$('evidence-form').elements.source.value.trim();if(!text)throw Error('先粘贴要选择的学习片段。');const fragments=text.split(/\n\s*\n/).filter(Boolean).slice(0,50).map((content,i)=>({id:'fragment-'+i,role:'user',content}));$('dialog')._fragments=fragments;$('evidence-fragments').innerHTML='<h3>只提交你勾选的片段</h3>'+fragments.map((m,i)=>`<label class="message-check"><input type="checkbox" name="fragment" value="${i}"><span><small>片段 ${i+1}</small><select name="role-${i}" aria-label="片段 ${i+1} 的说话人"><option value="user">我的话</option><option value="assistant">AI 回答</option></select><p>${h(m.content)}</p></span></label>`).join('')},
  'confirm-evidence':async()=>{const v=values('evidence-form');if(!v)return;const data=new FormData($('evidence-form'));const messages=data.getAll('fragment').map(i=>({...$('dialog')._fragments[Number(i)],role:data.get('role-'+i)||'user'})),assetIds=data.getAll('assetId');if(!messages.length&&!assetIds.length)throw Error('至少勾选一段对话或一份资料。');for(const assetId of assetIds){const asset=await action('getAsset',{assetId});messages.push({role:'user',content:titleOf(asset)+'\n'+(asset.markdown||asset.card?.instructions||'')})}await action('submitLearning',{courseId:courseData().id,title:v.title,messages});closeDialog();await changed('只提交了你选中的内容。')},
  'view-submission':b=>submissionDetail(b.dataset.id),
  'ask-assessment':async b=>{const c=courseData();closeDialog();await sendMessage(`请使用教学 Skill 分析课程 ${c.id} 的学习提交 ${b.dataset.id}。只基于学生主动提交的证据，区分已体现的理解、缺口和一次迁移检查；Token 不代表掌握程度。生成草稿，留给教师核验。`)},
  'confirm-review':async b=>{const v=values('review-form');if(!v)return;const s=byId(submissions(courseData()),b.dataset.id);await action('reviewSubmission',{submissionId:b.dataset.id,expectedAssessmentRevision:s.assessmentRevision||0,level:v.judgment,basis:v.feedback});closeDialog();await changed('教师核验已保存。')},
  'new-assignment':()=>assignmentForm(),
  'ask-assignment':async()=>{const c=courseData(),studentId=$('assignment-form').elements.studentId.value;if(!studentId)throw Error('先邀请至少一位学生加入。');const submission=submissions(c).find(s=>s.student?.id===studentId);closeDialog();await sendMessage(`请为课程 ${c.id} 的学生 ${studentId} 拟一份针对性作业。${submission?'先读取学习提交 '+submission.id+' 和教师已核验的反馈。':'先问教师具体要检查的理解缺口，不猜测学生水平。'}用 draft_targeted_assignment 保存为草稿，写清任务、应交成果、完成标准；不得直接发布，留给教师在面板确认。`)},
  'confirm-assignment':async()=>{const v=values('assignment-form');if(!v)return;if(!v.studentId)throw Error('先邀请至少一位学生加入。');let a=$('dialog')._assignment;if(!a){const result=await action('draftAssignment',{...v,courseId:courseData().id});a=result.assignment||result}else{const result=await action('draftAssignment',{assignmentId:a.id,courseId:courseData().id,expectedRevision:a.revision,...v});a=result.assignment||result}await action('publishAssignment',{assignmentId:a.id,expectedRevision:a.revision});closeDialog();await changed('作业已布置给所选同学。')},
  'view-assignment':b=>assignmentDetail(b.dataset.id),
  'submit-assignment':async b=>{const v=values('answer-form');if(!v)return;await action('submitAssignment',{assignmentId:b.dataset.id,expectedRevision:byId(assignments(courseData()),b.dataset.id)?.revision,content:v.content});closeDialog();await changed('作业已提交，等待老师核验。')},
  'complete-assignment':async b=>{const a=byId(assignments(courseData()),b.dataset.id);const basis=$('assignment-basis')?.value.trim();if(!basis)throw Error('写下依据，再确认作业完成。');await action('confirmAssignment',{assignmentId:b.dataset.id,expectedRevision:a.revision,basis});closeDialog();await changed('已确认完成。')},
  'feedback-form':async b=>{const id=b.dataset.id,publication=byId(state.community,id);openDialog('这张卡帮到了你吗？',`<form id="feedback-form"><h3>${h(publication.title)}</h3><label class="field">你的使用感受<select name="helped"><option value="yes">帮上忙了</option><option value="partly">有些帮助，还需要调整</option><option value="no">这次不太适合</option></select></label><label class="field">给这次体验打分<select name="rating"><option value="5">5 分</option><option value="4">4 分</option><option value="3">3 分</option><option value="2">2 分</option><option value="1">1 分</option></select></label><label class="field">哪里有用，哪里想改<textarea name="note" rows="4" maxlength="3000" placeholder="说一个具体的使用情境，会更有帮助。"></textarea></label><label class="check"><input name="confirmed" type="checkbox" required><span>确认分享这次使用感受。</span></label><p class="subtle">这是使用者自述，不作为学习效果的证明。</p></form>`,button('取消','close-dialog')+button('提交反馈','confirm-feedback','primary',`data-id="${h(id)}"`))},
  'confirm-feedback':async b=>{const v=values('feedback-form');if(!v)return;const p=byId(state.community,b.dataset.id);await action('addFeedback',{publicationId:p.id,version:p.version,rating:Number(v.rating),helped:v.helped,note:v.note});closeDialog();toast('反馈已保存，感谢你写下具体感受。')},
  'share-strategy':()=>shareForm(),
  'confirm-share':async()=>{const v=values('share-form');if(!v)return;await action('publishStrategy',{assetId:v.assetId,authorName:state.actor.label});closeDialog();await changed('卡片已分享，个人学习记录没有公开。')},
  'adopt-community':async b=>{const publication=await action('getCommunityStrategy',{publicationId:b.dataset.id});const draft=await action('createDraft',{kind:'strategy',card:{...publication.card,id:crypto.randomUUID(),parent:{id:publication.card.id,version:publication.card.version}}});await refresh();draftForm(draft)},
  'refresh':()=>refresh()
 };
 document.addEventListener('click',async event=>{const b=event.target.closest('button');if(!b||b.disabled)return;if(b.dataset.nav){tab=b.dataset.nav;render();return}const fn=handlers[b.dataset.action];if(!fn)return;b.disabled=true;$('dialog-error').textContent='';try{await fn(b)}catch(error){const message=error.message||'操作未完成，请重试。';if($('dialog').open)$('dialog-error').textContent=message;else toast(message)}finally{if(b.isConnected)b.disabled=false;reportSize()}});
 $('dialog').addEventListener('click',event=>{if(event.target===$('dialog')){const r=$('dialog').getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)closeDialog()}});
 const reduced=matchMedia('(prefers-reduced-motion: reduce)');
 document.addEventListener('pointermove',event=>{if(reduced.matches||event.pointerType!=='mouse')return;const c=event.target.closest('.strategy-card');if(!c)return;const r=c.getBoundingClientRect(),x=(event.clientX-r.left)/r.width-.5,y=(event.clientY-r.top)/r.height-.5;c.dataset.tilt='true';c.style.transform=`perspective(800px) rotateX(${-y*3}deg) rotateY(${x*4}deg) translateY(-3px)`});
 document.addEventListener('pointerout',event=>{const c=event.target.closest('.strategy-card');if(c&&!c.contains(event.relatedTarget)){c.style.transform='';delete c.dataset.tilt}});
 window.addEventListener('message',event=>{if(event.source!==parent||event.data?.jsonrpc!=='2.0')return;if(parentOrigin!=='*'&&event.origin!==parentOrigin)return;const m=event.data;if(m.id!=null&&!m.method&&pending.has(m.id)){const p=pending.get(m.id);pending.delete(m.id);clearTimeout(p.timer);if(parentOrigin==='*'&&event.origin!=='null')parentOrigin=event.origin;m.error?p.reject(Error(m.error.message||'宿主操作未完成')):p.resolve(m.result);return}if(m.method==='ui/notifications/tool-result'){try{const next=unpack(m.params);if(next?.strategies||next?.workspace)merge(next);else if(next?.draft){state.drafts=[{...next.draft,title:titleOf(next.draft)},...state.drafts.filter(d=>d.id!==next.draft.id)];render()}else refresh().catch(()=>{})}catch(error){toast(error.message)}}if(m.method==='ui/notifications/host-context-changed'&&m.params?.theme){document.documentElement.dataset.hostTheme=m.params.theme}if(m.method==='ui/resource-teardown'&&m.id!=null){for(const p of pending.values()){clearTimeout(p.timer);p.reject(Error('学习面板已关闭。'))}pending.clear();parent.postMessage({jsonrpc:'2.0',id:m.id,result:{}},parentOrigin)}});
 (async()=>{try{await rpc('ui/initialize',{appInfo:{name:'LearnFlow学习流动',version:'0.3.0'},appCapabilities:{},protocolVersion:'2026-01-26'});ready=true;notify('ui/notifications/initialized');await refresh();$('connection-status').textContent='';if(!state.preferences.onboardingComplete&&!state.preferences.intent){questionIndex=0;answers={};showQuestion()}}catch(error){$('view').innerHTML=empty('这一步，需要学习助手一起。',error.message,button('重新连接','refresh','soft'));$('connection-status').textContent='在支持 MCP Apps 的 Buddy 预览中打开，或使用本地协议预览。'}})();
})();
